name:                hakyll-date
version:             0.1.0.0
github:              "dmp1ce/hakyll-date"
license:             PublicDomain
author:              "David Parrish"
maintainer:          "daveparrish@tutanota.com"

data-dir: data

extra-source-files:
- README.md
- ChangeLog.md
- test/data/posts/2018-09-28-fall-prep.md

# Metadata used when publishing your package
synopsis:            Additional date functions for Hakyll
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hakyll-date#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - hakyll
  - time

tests:
  hakyll-date-test:
    main:                TestSuite.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hakyll-date
    - hakyll
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - unordered-containers
    - containers >= 0.5.7 && < 0.6
